### ISSUE TITLE
Indexing Variable Out of Bounds

### ISSUE THREAD

**Issue by pulsipher** [exanauts/ExaModels.jl#32]
I noticed that users can accidently index a variable out of bounds which could lead to silent bugs.
```julia
julia> using ExaModels

julia> c = ExaCore();

julia> x = variable(c, 1:3);

julia> y = variable(c, 1:2);

julia> x[2] # accesses the variable we expect
ExaModels.Var{Int64}(2)

julia> x[4] # actually accesses y[1] and will probably lead to unintentional problems
ExaModels.Var{Int64}(4)
```
I would suggest erroring if the index violates the dimension of the variable.

**Comment by sshin23** [comment]
Handling direct indexing like
```
x[2]
```
should be straightforward, but when this happens in the objective and constraint, like
```
constraint(c, x[i] for i =1:4)
```
it can be a bit tricky to check the index because we don't actually run the for loop until the first call. And in the actual call (e.g., function or derivative evaluation), we use `@inbounds` to maximize the performance. I think we should implement a separate `boundcheck` function (not called in each derivative evaluation call, but just called once when model is created) to check the index bounds.
